// problem0002.cpp
// Project Euler Problems
// author: beefviper
// date: Sept 14, 2026

#include "problems.h"

static const std::string title{ "Even Fibonacci numbers" };

static const std::string body{ R"(
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
)" };


uint64_t problem2()
{
	uint64_t result{ 0 };

	uint64_t index{ 1 };
	uint64_t number{ 0 };
	uint64_t max{ 4000000 };

	while ( result < max ) {
		number = fib(index);
        print << number << ", ";
		if (number % 2 == 0) {
			result += number;
		}
		index++;
	}
    print << std::endl << result << std::endl;

    return result;
}

static const std::optional<uint64_t> answer{ 4613732 };

static const ProblemRegistrar problem2_registrar{ Problem{ 2, title, body, problem2, answer } };
