// problem0002.cpp
// Project Euler Problems
// author: beefviper
// date: Sept 14, 2026

#include "problems.h"

#include "eulerlib.h"
#include "print.h"

#include <string>
#include <cstdint>

namespace pe = ProjectEuler;

static const uint64_t number{ 2 };

static const std::string title{ "Even Fibonacci numbers" };

static const std::string question{ R"(
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
)" };

static uint64_t solution()
{
	uint64_t result{ 0 };

	uint64_t index{ 1 };
	uint64_t number{ 0 };
	uint64_t max{ 4000000 };

	while ( result < max ) {
		number = pe::fib(index);
        pe::print << number << ", ";
		if (number % 2 == 0) {
			result += number;
		}
		index++;
	}

    return result;
}

static const std::string answer{ "The sum is: {}" };

static const pe::ProblemRegistrar problem_registrar{ number, title, question, solution, answer };
