// problem0012.cpp
// Project Euler Problems
// author: beefviper
// date: Sept 14, 2026

#include "problems.h"
#include "print.h"
#include "eulerlib.h"

#include <string>
#include <vector>

namespace pe = ProjectEuler;

static const pe::value number{ 12 };

static const std::string title{ "Highly divisible triangular number" };

static const std::string question{ R"(
The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
)" };

static pe::value solution()
{
	pe::value result{ 0 };
	pe::value numberOfFactors = 0;
	pe::value counter = 1;
	pe::value maxFactors = 500;
	std::vector<pe::value> factors;

	while (numberOfFactors < maxFactors) {
		result += counter;
		factors = pe::getFactors(result);
		numberOfFactors = factors.size();
		counter++;
	}

    pe::print << "The first tringle number with " << numberOfFactors
		<< " factors is " << result << pe::endl;

    return result;
}

static const std::string answer{ "The first triangle number with over five hundred divisors is: {}" };

static const pe::value expected{ 76576500 };

static const pe::ProblemRegistrar problem_registrar{ number, title, question, solution, answer, expected };
