// Problem0002.cpp : Defines the entry point for the console application.

/*
Problem 2: Even Fibonacci numbers

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.

Answer: 4613732
*/

#include "ProjectEuler.h"

uint64_t problem2()
{
	uint64_t result{ 0 };

	uint64_t index{ 1 };
	uint64_t number{ 0 };
	uint64_t max{ 4000000 };

	while ( result < max ) {
		number = fib(index);
		//std::cout << number << ", ";
		if (number % 2 == 0) {
			result += number;
		}
		index++;
	}
	//std::cout << std::endl << result << std::endl;

    return result;
}
