// problem0012.cpp
// Project Euler Problems
// author: beefviper
// date: Sept 14, 2026

#include "problems.h"

static const std::string title{ "Highly divisible triangular number" };

static const std::string body{ R"(
The sequence of triangle numbers is generated by adding the natural
numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

1: 1
3: 1,3
6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred
divisors?
)" };

uint64_t problem12()
{
	uint64_t result{ 0 };
	uint64_t numberOfFactors = 0;
	uint64_t counter = 1;
	uint64_t maxFactors = 500;
	std::vector<uint64_t> factors;

	while (numberOfFactors < maxFactors) {
		result += counter;
		factors = getFactors(result);
		numberOfFactors = factors.size();
		counter++;
	}

    print << "The first tringle number with " << numberOfFactors
		<< " factors is " << result << std::endl;

    return result;
}

static const std::optional<uint64_t> answer{ 76576500 };

static const ProblemRegistrar problem12_registrar{ Problem{ 12, title, body, problem12, answer } };
